### ISSUE TITLE
Memory leak in `ui.line_plot`?

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#124]
The NiceGUI documentation at https://nicegui.io is written with NiceGUI itself. So it's a good testbed to see how well the lib performs with a lot of visitors. One thing we see quite regular is this error message:

> /usr/local/lib/python3.10/site-packages/nicegui/elements/plot.py:18: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.

When looking at the code, the `ui.plot` seems to be ok. By default figures are closed when their context is exited. But with `ui.line_plot` [new data can be added to the plot](https://github.com/zauberzeug/nicegui/blob/782124cb11097fa571dfec3328108040ff752a60/nicegui/elements/line_plot.py#L33). Could this be the root cause of the warning?

- [ ] Close open plots on disconnect (of a private page).

**Comment by falkoschindler** [comment]
I checked the memory usage for three different elements: `ui.label`, `ui.plot` and `ui.line_plot`.

```python
label = ui.label()

def update():
    label.text = str(time.time()) * 1000

    gc.collect()
    process = psutil.Process(os.getpid())
    print(f'{process.memory_info().rss:_}')

ui.timer(0.1, update)
```

```python
plot = ui.plot(close=False)

def update():
    with plot:
        pl.clf()
        pl.plot(1, time.time(), 'o')

    gc.collect()
    process = psutil.Process(os.getpid())
    print(f'{process.memory_info().rss:_}')

ui.timer(0.1, update)
```

```python
line_plot = ui.line_plot(limit=100)

def update():
    line_plot.push([time.time()], [[1]])

    gc.collect()
    process = psutil.Process(os.getpid())
    print(f'{process.memory_info().rss:_}')

ui.timer(0.1, update)
```

The behavior is pretty similar. After rapid growth in the beginning, the memory usage only grows a few kB now and then. That still looks like a leak. But as long as we can't eliminate something like https://github.com/justpy-org/justpy/issues/547 in JustPy or Starlette, it's hard to strictly analyze NiceGUI elements.

**Comment by falkoschindler** [comment]
Reproduction of @rodja's original RuntimeWarning:

```python
for i in range(30):
    ui.line_plot()
```

Or with `ui.plot`:

```python
for i in range(30):
    with ui.plot(close=False):
        pass
```

**Comment by falkoschindler** [comment]
Unfortunately this warning also comes up when using `ui.plot(close=True)` without opening and closing a context:

```python
for i in range(30):
    ui.plot()
```

**Comment by falkoschindler** [comment]
The warning about more than 20 open figures is ok and informs the user about the inherent memory limitation.

But we should close open figures when private pages get disconnected. This will be the main task of this issue.

Reproduction: Reloading the following page shows the warning, although only 15 figures should be open at each point in time.

```python
@ui.page('/')
def page():
    for i in range(15):
        with ui.plot(close=False):
            ...
```

**Comment by falkoschindler** [comment]
@rodja As proposed in [my last comment](https://github.com/zauberzeug/nicegui/issues/124#issuecomment-1293499187) I implemented an auto-closing mechanism for `ui.plot` when the client disconnects (i.e. is removed from the global client dictionary): https://github.com/zauberzeug/nicegui/commit/7e16877d0f7c87c2d9b4e65ec039d377e873f05a. Can you, please, have a look?

It can be tested using the following page with 10 plots that are kept open with `close=False`:

```python
@ui.page('/')
def page():
    for _ in range(10):
        with ui.plot(close=False):
            plt.plot([1, 2])
```

Without the auto-reload task there is a warning "More than 20 figures have been opened." after reloading the page twice. With the auto-reload task the warning is gone.

**Comment by rodja** [comment]
Looks great and works as expected. Of course the warning still appears if multiple tabs are opened with your test code.
