### ISSUE TITLE
textinput can't display in native model but in terminal (same issue with #1205)

### ISSUE THREAD

**Issue by wllbll** [zauberzeug/nicegui#1792]
### Description

Same with #1205 
when i use native mode to start the program, i found that, the input element don't work, and my input display in the terminal.
the problem occurs on mac os, following is my versions：
> Monterey 12.6.3
> Python 3.10.13
> nicegui 1.3.16
> pywebview 4.3.3

And I tried the code in comment https://github.com/zauberzeug/nicegui/issues/1205#issuecomment-1647503872 

recap, i tried 2 version 
create_window_pywebview.py

```python
import webview

html = """
<html>
<head>
    <title>Text Input Example</title>
</head>
<body>
    <h1>Text Input Example</h1>
    <input type="text" id="input-field" placeholder="Enter your text here">
</body>
</html>
"""

webview.create_window("Text Input Example", html=html)
webview.start(debug=True)
```
create_window_nicegui.py

```python
from nicegui import ui

ui.input(label='input here')
ui.run(native=True)
```
when I start window below( using pythonw instead of python) ,the input issue doesn't show
```shell
pythonw create_window_nicegui.py
```

when I started window below( still using pythonw), the input issue arise

```shell
pythonw create_window_webview.py
```

**Comment by wllbll** [comment]
for your reference, I make a screen shot , and you can see another issue: the window show in background when start with nicegui

https://github.com/zauberzeug/nicegui/assets/2107853/fad8cdc7-3220-4e01-b722-d4d4ac14d6d2

**Comment by falkoschindler** [comment]
@wllbll Can you please clarify:
- You write "different with #1205" in the title and "same with #1205" in the description. What do you mean?
- You write with `pythonw create_window_webview.py` the issue doesn't show, and with `pythonw create_window_webview.py` the issue arises. That's the same code.
- And I can't see the input issue in the screen cast. The input field seems to work. (The window being opened in the background is unrelated with the input field and probably something we can't change.)

**Comment by wllbll** [comment]
@falkoschindler  sorry to make you confusing, i corrected my miswritten.
To recap, my issue is, it display the input in _input element_ when start with ```pythonw create_window_webview.py```, but can't display the display in _input element_ when start with ```pythonw create_window_webview.py```  (please notice the input element in my screen cast)

**Comment by falkoschindler** [comment]
Sorry, I still don't get it. Let's read your sentence again:
> it display the input in _input element_ when start with `pythonw create_window_webview.py`, but
> can't display the display in _input element_ when start with `pythonw create_window_webview.py`

"display the input" works, and
"display the display" doesn't?
What does that mean?

**Comment by wllbll** [comment]
> Sorry, I still don't get it. Let's read your sentence again:
> 
> > it display the input in _input element_ when start with `pythonw create_window_webview.py`, but
> > can't display the display in _input element_ when start with `pythonw create_window_webview.py`
> 
> "display the input" works, and "display the display" doesn't? What does that mean?

Sorry again for my English. :(

You can see from screen cast.

The input character was displayed in input element when i click the keyboard, which is the normal behavior.
But when i start the program with ```pythonw create_window_webview.py``` , the input element don't display the character.

This issue occur in #1205 , and maybe it caused by pywebview, therefore i created two scripts to make comparison, as suggest by your comment on #1205.

**Comment by wllbll** [comment]
> Ok, `pythonw create_window_pywebview.py` from [#1205 (comment)](https://github.com/zauberzeug/nicegui/issues/1205#issuecomment-1647503872) works, but `pythonw create_window_nicegui.py` doesn't. That's strange!
> 
> I'm a bit out of ideas, but I have some more questions:
> 
> * Does it also occur with `python` instead of `pythonw`?
> * On [textinput can't display in native model but in terminal #1205 (comment)](https://github.com/zauberzeug/nicegui/issues/1205#issuecomment-1760672619) you said "I seems this issue related to conda". Why do you think that?
> * Just to be sure: Does the problem also occur with a _real_ keyboard?

1. It works neither when tried with ```python```,  which means input characters doesn't display in both scripts
2. I searched threads relating to 'MacOS input' in _pywebview_ project, someone said it related with conda.  I didn't try to run two scripts directly outside of conda environment, but i tried to packaged by `pyinstall` and run, the input element works.
3. The problem also occur with real key board, I just want show what happen with virtual keyboard in my screen cast.

**Comment by falkoschindler** [comment]
Thanks for the additional information, @wllbll.

I'm clueless whether it's a MacOS, pywebview or NiceGUI problem. Or could it be related to some language or keyboard setting? As far as I remember all reports came from Chinese machines... 🤔

Can anyone else reproduce this problem or proof me wrong that it is caused by some system setting? Thanks a lot!

**Comment by wllbll** [comment]
Another trial: I changed my Preferred languages into English in my MacOS, issue still happen. :(

**Comment by falkoschindler** [comment]
@wllbll pywebview 4.4 just got released and in their release notes I spotted https://github.com/r0x0r/pywebview/issues/1187: "Issue with window focus on keystrokes in macOS". Can you check if the problem still occurs with pywebview 4.4? Thanks!

**Comment by wllbll** [comment]
> @wllbll pywebview 4.4 just got released and in their release notes I spotted [r0x0r/pywebview#1187](https://github.com/r0x0r/pywebview/issues/1187): "Issue with window focus on keystrokes in macOS". Can you check if the problem still occurs with pywebview 4.4? Thanks!

Yeh, "maybe" it work after updating pywebview 4.4 , As the input issue did not occur when ```python create_window_pywebview.py``` and the window popped up in foreground instead of background,  but there is no elements within window after run ```python  create_window_nicegui.py```( the window popped up in foreground too), therefore i wrote 'maybe' . 
Beside, i update the nicecegui to 1.4.1, still, i can't see any elements in window,  the there are errors in console, but i guess this should be another issue related to latest pywebview
 
<img width="798" alt="截屏2023-10-29 10 28 19" src="https://github.com/zauberzeug/nicegui/assets/2107853/a936af8d-2e5e-4b60-8f8a-d373c3e132b3">

**Comment by falkoschindler** [comment]
Ok, this looks like a different problem. Does NiceGUI work with your Safari version (with `native=False`)?

There seems to be a problem with loading TailwindCSS. We had an [issue](https://github.com/zauberzeug/nicegui/issues/1506) with old iOS version, maybe that's another incompatibility with old browsers.

Can you try running `create_window_nicegui.py` with `native=True` but `tailwind=False`? This could allow you to check the input and focus problem.

**Comment by falkoschindler** [comment]
I'll close this issue, because I think the original problem is solved.
But feel free to open a new issue for the blank page you encountered.
