### ISSUE TITLE
Exception after v1.4.14

### ISSUE THREAD

**Issue by MuuXB** [zauberzeug/nicegui#4194]
### Description

I found that when I upgraded from version 1.4.14 to 1.4.15, the previous bug appeared #2354. After checking the commit, I found that some changes were made here #2521 . Was “_nicegui_ws” omitted? 

My service is started using uvicorn. Will there be any conflicts?, when I add "_nicegui_ws", it works
```py
uvicorn.run(server, host=host, port=port, root_path=f"xxxxx/xxxxx")
```

Should 
```sio_app = SocketIOASGIApp(socketio_server=sio, socketio_path='/socket.io')```
change to？
```sio_app = SocketIOASGIApp(socketio_server=sio, socketio_path='/_nicegui_ws/socket.io')```

**Comment by rodja** [comment]
I vaguely remember that an FastAPI update lead us to #2521. So if you encounter a similar error you may need to take extra care which FastAPI and socketio dependencies you install. It was a mess and I think in later versions the issue is fixed once and for all. Why do you not upgrade to 2.x?

**Comment by MuuXB** [comment]
> I vaguely remember that an FastAPI update lead us to #2521. So if you encounter a similar error you may need to take extra care which FastAPI and socketio dependencies you install. It was a mess and I think in later versions the issue is fixed once and for all. Why do you not upgrade to 2.x?

Yes, I tried using the latest package but still encountered errors. I reviewed the commit history and found that this code caused the issue. In my program, when I start Uvicorn with the root_path parameter specified, the error is reproduced. If I remove the root_path, it runs normally. Therefore, I pointed out that I think this change is a problem.

```uvicorn.run(server, host=host, port=port, root_path=f"xxxxx/xxxxx")```

**Comment by rodja** [comment]
Do you have a full [minimum reproducible code example](https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-it-important-to-provide-a-minimal-reproducible-example)? That way we could try it ourself and go deeper.

**Comment by falkoschindler** [comment]
I'm closing this issue due to inactivity. Feel free to reopen if you have new information.
