### ISSUE TITLE
Leaflet plugins not working

### ISSUE THREAD

**Issue by jacksonhshields** [zauberzeug/nicegui#5317]
### First Check

- [x] I added a very descriptive title here.
- [x] This is not a Q&A. I am sure something is wrong with NiceGUI or its documentation.
- [x] I used the GitHub search to find a similar [issue](https://github.com/zauberzeug/nicegui/issues) and came up empty.

### Example Code

```python
from nicegui import ui

m = ui.leaflet((51.51, -0.09), additional_resources=[
    'https://unpkg.com/leaflet-rotatedmarker@0.2.0/leaflet.rotatedMarker.js',
])
m.marker(latlng=(51.51, -0.091), options={'rotationAngle': -30})
m.marker(latlng=(51.51, -0.090), options={'rotationAngle': 30})

ui.run()
```

### Description

I am trying to use leaflet plugins to add more functionality to my leaflet app. The example from the documentation for loading plugins is not working and the markers show up on rotated. I've been also trying to use layer control plugins which wasn't working, so hoping a fix from this will also fix that.

The console errors on the browser are:

> Uncaught ReferenceError: L is not defined
    at leaflet.rotatedMarker.js:3:26
    at leaflet.rotatedMarker.js:57:3Understand this error

### NiceGUI Version

3.0.4

### Python Version

Python 3.10.12

### Browser

Chrome

### Operating System

Linux

**Comment by evnchn** [comment]
Hello @jacksonhshields thanks for the report. 

Most certainly fixed by #5281, I wrote it so I know it. 

As such, please wait for 3.1 release and the problem should go away. 

If not, you can consider the patch mentioned in #5279.

**Comment by jacksonhshields** [comment]
Thank you. Happy to wait to the 3.1 release. I did try adding draw control and the problem is still there?

**Comment by evnchn** [comment]
> I did try adding draw control and the problem is still there?

Then it's a different story. Will look into it when free.
